### ISSUE TITLE
还要不要脸，有没有底线？？？？

### ISSUE THREAD

**Issue by ieliwb** [tophubs/to-be-slack#11]
网站名称一模一样，域名也完全一模一样山寨？？？

**Comment by ttop5** [comment]
本站源于 v2ex 上兴起的互联网热榜，独立开发，免费开源，欢迎使用。气不气？

**Comment by ieliwb** [comment]
你开源没人阻止你，我的站：
今日热榜 https://tophub.today/

你叫今日热榜也没关系，是你的自由，你搞个克隆域名tophub.fun都这么山寨，有底线吗？
