### ISSUE TITLE
你开源没人阻止你，我的站： 今日热榜 https://tophub.today/  你叫今日热榜也没关系，是你的自由，你搞个克隆域名tophub.fun都这么山寨，有底线吗？

### ISSUE THREAD

**Issue by ieliwb** [tophubs/to-be-slack#12]
你开源没人阻止你，我的站：
今日热榜 https://tophub.today/

你叫今日热榜也没关系，是你的自由，你搞个克隆域名tophub.fun都这么山寨，有底线吗？

**Comment by ttop5** [comment]
你没注册的域名别人就不能注册了么？再说了内容大家都是爬虫搞的，你打你的广告，我开我的源码。另外，域名是我和 @timeromantic 一起注册的。你也别见人就咬，烦得很。

**Comment by timeromantic** [comment]
别和他置气，不用管他，法律范围内的事情，又没犯法，用不着和他多说。



---原始邮件---
发件人: "回家看动画"<notifications@github.com>
发送时间: 2019年8月22日(星期四) 中午12:52
收件人: "tophubs/to-be-slack"<to-be-slack@noreply.github.com>;
抄送: "timeromantic"<1401698880@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [tophubs/to-be-slack] 你开源没人阻止你，我的站： 今日热榜 https://tophub.today/  你叫今日热榜也没关系，是你的自由，你搞个克隆域名tophub.fun都这么山寨，有底线吗？ (#12)



你没注册的域名别人就不能注册了么？再说了内容大家都是爬虫搞的，你打你的广告，我开我的源码。另外，域名是我和 @timeromantic 一起注册的。你也别见人就咬，烦得很。

**Comment by ieliwb** [comment]
https://whois.aliyun.com/whois/domain/tophub.fun?spm=5334.7477273.3.1
注册日期 | 2019年07月02日
还要打脸不
