### ISSUE TITLE
【Bug】百度贴吧的链接错误

### ISSUE THREAD

**Issue by zuoRambo** [tophubs/to-be-slack#5]
![image](https://user-images.githubusercontent.com/4715122/62937073-0f724280-bdfe-11e9-99f7-fa86d346686d.png)
![image](https://user-images.githubusercontent.com/4715122/62937085-1a2cd780-bdfe-11e9-893c-cafff197b990.png)

现在的链接 `http://tieba.baidu.com/hottopic/browse/hottopic?topic_id=272073&amp;topic_name=老友记将在影院上映`

应该是`http://tieba.baidu.com/hottopic/browse/hottopic?topic_id=272073&topic_name=老友记将在影院上映`

其他也都有问题。

**Comment by ttop5** [comment]
@zuoRambo 感谢反馈哈，我会找时间尽快修复。

**Comment by zuoRambo** [comment]
ok

**Comment by ttop5** [comment]
最近比较忙，我解决了再close

**Comment by ttop5** [comment]
已在新版中修复
